apiVersion: v1
kind: Service
metadata:
  name: querygenai-service
spec:
  type: NodePort
  selector:
    app: querygenai
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30007
